name: open_peeps_widgetbook
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  open_peeps: ^0.0.1
  widgetbook: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true